// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwpqfckqfwtasgusozin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cHFmY2txZnd0YXNndXNvemluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NTc3NTgsImV4cCI6MjA1MzIzMzc1OH0.OnHxCIWJwEt1nIZcC5-HSdo67e9Fa7y0AeEpOTwyHoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);