// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xenarugqrwktzmcwpxcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbmFydWdxcndrdHptY3dweGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MDM2NjksImV4cCI6MjA1MzI3OTY2OX0.DWO5GcBiaBIQsoF_RzC283gPmigEj2HhhZkIaikY3ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);